language: node_js
sudo: false
node_js:
- '7'
branches:
  only:
  - master
addons:
  apt:
    packages:
      - sshpass
before_script:
  - npm install
script:
  - npm run webpack
after_success:
  - sshpass ssh -o StrictHostKeychecking=no $DEPLOY_USER@$DEPLOY_HOST "cd $DEPLOY_PATH && ./deploy.sh" 
