language: node_js
sudo: false
node_js:
- '7'
branches:
  only:
  - master
before_script:
  - npm install
script:
  - npm run webpack
after_success:
  - mkdir archive
  - mv * archive
  - tar -czf package.tgz archive
  - ssh -o "StrictHostKeyChecking no" $DEPLOY_USER@$DEPLOY_HOST
  - cat $DEPLOY_PATH/deploy.sh