language: node_js
sudo: false
node_js:
- '7'
branches:
  only:
  - master
addons:
  apt:
    packages:
      - sshpass
before_script:
  - npm install
script:
  - npm run webpack
after_success:
  - mkdir archive
  - mv * archive
  - tar -czf package.tgz archive
  - scp package.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
  - sshpass ssh -o StrictHostKeychecking=no $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_PATH/deploy.sh
